package bg.dev.camel.routes

import bg.dev.camel.service.AiSummarizerService
import org.apache.camel.builder.RouteBuilder
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.context.annotation.Profile
import org.springframework.stereotype.Component

/**
 * DEMO 08 — AI Document Summariser
 *
 * Concepts shown:
 *  - File-to-file pipeline enriched by AI in the middle
 *  - Storing AI output alongside the original (fileName header manipulation)
 *  - Error handling with onException — AI calls can fail, routes should not crash
 *  - How Camel orchestrates: File IN → AI → File OUT (no custom glue code)
 *
 * Drop any .txt document into input/documents/.
 * A .summary.txt file appears in output/summaries/.
 *
 * Run with: -Dspring.profiles.active=demo08
 */
@Component
@Profile('demo08')
class Demo08_AiSummarizerRoute extends RouteBuilder {

  @Autowired
  AiSummarizerService summarizerService

  @Override
  void configure() {

    onException(Exception)
      .handled(true)
      .log('AI error for ${header.CamelFileName}: ${exception.message}')
      .to('file:output/summaries/errors')

    from('file:input/documents?noop=true&include=.*\\.txt&delay=5000')
      .routeId('ai-summariser')
      .log('📄 Summarising: ${header.CamelFileName}')
      .convertBodyTo(String)
      .process { exchange ->
        String content = exchange.in.getBody(String)
        String fileName = exchange.in.getHeader('CamelFileName', String)
        String summary = summarizerService.summarize(content)
        exchange.in.body = """
          DOCUMENT: ${fileName}
          ═══════════════════════════════════════
          
          SUMMARY:
          ${summary}
          
          ───────────────────────────────────────
          (Generated by Apache Camel + Spring AI)
          """.toString()
        String baseName = fileName.replaceAll(/\.[^.]+$/, '')
        exchange.in.setHeader('CamelFileName', baseName + '.summary.txt')
      }
      .log('   Summary:\n${body}')
      .to('file:output/summaries')
      .log('   ✓ Written to output/summaries/')
  }
}
